git_manage_django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('managesys.urls'))
]

managesys/urls.py
from django.urls import path
from . import views

app_name="managesys"
urlpatterns = [
    path('create',views.create,name='creation'),
    path('instructions',views.instructions,name='instructions'),
    path('',views.index,name='index')
]

managesys/models.py
from django.db import models

# Create your models here.

managesys/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.static import serve
import os


# Create your views here.

def create_repo(repo_name):
    os.system("mkdir /tmp/git/{0}.git&&git init --bare /tmp/git/{0}.git".format(repo_name))

def index(request):
    return render(request,'managesys/index.html',{})

def create(request):
    return render(request,'managesys/create.html',{})

def instructions(request):
    repo_name=request.POST['repo_name']
    create_repo(repo_name)
    return render(request,'managesys/instruction.html',{"repo_name":repo_name})

managesys/templates/managesys/create.html
<!DOCTYPE html>

<head>
    <meta charset="utf-8">
</head>

<body>
    <h1>自分のリポジトリをつくろう！</h1>
    <form action="{% url 'managesys:instructions'%}" method="POST">
        {% csrf_token %}
        レポジトリ名<input type="text" name="repo_name">
        <input type="submit" value="提出">
    </form>
</body>

managesys/templates/managesys/index.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
</head>

<body>
    <h1>ようこそNGC中央リポジトリへ</h1>
    <div>
        このページはNGC中央リポジトリのホームページです。一旦中止され、いまは再開になります。
        このページを介して、リポジトリの追加と削除はできる。そして、リポジトリの所有者情報と
        ページの詳細は見られる。
    </div>
    <form action="{% url 'managesys:creation' %}" method="GET">
        <input type="submit" value="Create">
    </form>
</body>

managesys/templates/managesys/instruction.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
</head>

<body>
    <h1>リポジトリ{{repo_name}}の設立出来ました！</h1>
    <div>
        サーバにリポジトリは既に用意してあります。ローカルレポジトリからリモートを初期化してください。指示どおりにやってください。
    </div>
    <div>
        ターミナルに以下の命令を実行する。
        <ol>
            <li>
                git remote add origin git@name-of-this-host:~/git/{{ repo_name }}.git
            </li>
            <li>
                git push -u origin master
            </li>
        </ol>
    </div>
    <form action="{% url 'managesys:creation' %}" method="GET">
        <input type="submit" value="もう一つリポジトリを作る">
    </form>
</body>